const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');
const { isActionModelGuild, hasManageGuild } = require('../utils/permissions');
const { getSettings } = require('../services/actionModelSettingsService');
const { generateCodes } = require('../services/accessCodeService');
const { logToGuild } = require('../services/logService');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('generate-codes')
    .setDescription('[Action Model only] Generate one-time-use Alpha/campaign access codes.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
    .addIntegerOption((opt) =>
      opt
        .setName('amount')
        .setDescription('How many codes to generate (max 100)')
        .setRequired(true)
        .setMinValue(1)
        .setMaxValue(100)
    ),

  async execute(interaction) {
    if (!isActionModelGuild(interaction.guildId)) {
      await interaction.reply({ content: '🔒 This command is only available in the Action Model server.', ephemeral: true });
      return;
    }
    if (!hasManageGuild(interaction)) {
      await interaction.reply({ content: '🔒 You need the Manage Server permission to use this.', ephemeral: true });
      return;
    }

    const settings = await getSettings();
    if (!settings.campaignRoleId) {
      await interaction.reply({
        content: '⚠️ No campaign/Alpha role is configured yet. Run `/setup panel` and set one first.',
        ephemeral: true,
      });
      return;
    }

    const amount = interaction.options.getInteger('amount');
    await interaction.deferReply({ ephemeral: true });

    const codes = await generateCodes({
      guildId: interaction.guildId,
      amount,
      roleId: settings.campaignRoleId,
      roleName: settings.campaignRoleName || settings.campaignRoleId,
      createdByUserId: interaction.user.id,
    });

    const codeBlock = codes.map((c) => c.code).join('\n');
    await interaction.editReply({
      content: `🎟️ Generated ${codes.length} code(s) for **${settings.campaignButtonLabel}**:\n\`\`\`\n${codeBlock}\n\`\`\``,
    });

    await logToGuild(
      interaction.client,
      interaction.guildId,
      '🎟️ Codes Generated',
      `${codes.length} code(s) generated by <@${interaction.user.id}> for role <@&${settings.campaignRoleId}>`
    );
  },
};
